obstacle_range: 5.0 # 3.0
raytrace_range: 6.0 # 3.5
footprint: [[-0.35, -0.30], [-0.35, 0.30], [0.35, 0.30], [0.35, -0.30]]
#robot_radius: 0.105
inflation_radius: 0.8
cost_scaling_factor: 3.0 #3.0
map_type: costmap
observation_sources: scan
scan: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}
