<?xml version='1.0'?>
<robot name="skid_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_x_offset" value="0" />
  <xacro:property name="laser_width" value="0.1" />
  <xacro:property name="laser_length" value="0.1" />
  <xacro:property name="laser_height" value="0.1" />

  <xacro:property name="scale" value="1" />

  <xacro:property name="mower_height" value="${scale * 0.3}" />
  <xacro:property name="mower_length" value="${scale * 0.46}" />

  <xacro:property name="hardware_length" value="${mower_length/2.0}" />
  <xacro:property name="hardware_height" value="${mower_height/2.0}" />

  <xacro:property name="laser_x_offset" value="${base_x_offset}" />
  <xacro:property name="laser_z_offset" value="${hardware_height + 0.025}" />
  

  <xacro:property name="camerra_width" value="0.05" />
  <xacro:property name="camerra_length" value="0.05" />
  <xacro:property name="camerra_height" value="0.05" />
  <xacro:property name="camerra_x_offset" value="${hardware_length/2.0 + base_x_offset - camerra_length/2.0 + 0.001}" />
  <xacro:property name="camerra_z_offset" value="${hardware_height - camerra_height/2.0 + 0.001}" />
  

  <!--Camera model -->
  <link name='camera'>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"/>
    </inertial>
    <collision name='camera_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${camerra_length} ${camerra_width} ${camerra_height}"/>
      </geometry>
    </collision>
    <visual name='camera_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${camerra_length} ${camerra_width} ${camerra_height}"/>
      </geometry>
      <material name="brown"/>
    </visual>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="${camerra_x_offset} 0 ${camerra_z_offset}" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>  

  
  <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
  <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
  <link name="imu_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.01"/>
      </geometry>
    </collision>
      <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.01"/>
      </geometry>  
      <material name="red"/> 
      </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="imu_link" />
  </joint>

  <!-- hokuyo sensor-->
  <link name='hokuyo'>
    <pose>0 0 0 0 0 0</pose>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6" />
    </inertial>
    <collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${laser_length} ${laser_width} ${laser_height}"/>
      </geometry>
    </collision>
    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://skid_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${laser_x_offset} 0 ${laser_z_offset}" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>  
    

</robot>
